[package]
name = "rp"
version = "0.1.0"
edition = "2021"

[lib]
name = "rp"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.3", features = ["extension-module", "full"] }
numpy = "0.17.2"
